# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

# Shared secrets are available across all environments.

# shared:
#   api_key: a1B2c3D4e5F6

# Environmental secrets are only available for that specific environment.

development:
  secret_key_base: f91e7e69213e94995367977334d6f3d3f62e8526c98867b98000b0cdde827d4734a4d5b59a0a434cc265741e753271f4032a0f9a54ab3b530c1d451705ce69d9

test:
  secret_key_base: 2296b7a9100034674a3465620fa1006eb6be146af9fa13c306d8e368551301ba3cc7f179ff322a91899801e94bbe4b32c01dcf564db8af8e8e292889b2d2d8e8

# Do not keep production secrets in the unencrypted secrets file.
# Instead, either read values from the environment.
# Or, use `bin/rails secrets:setup` to configure encrypted secrets
# and move the `production:` environment over there.

production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
